### PR TITLE
fixing lint errors

### PR DESCRIPTION
**Pull request by kirstyellis**

### CODE REVIEW

**Comment by ugocupcic** [comment]
Thanks for the effort but there are still lots of lint errors on circle ci. Shall I wait for you to finish cleaning them? I'm happy to merge that one already otherwise.

**Comment by kirstyellis** [comment]
I have done more changes and trying to work through them, there are a lot. It is finding errors in the RoNex protocols which Toni said we do not want to change, so can we skip these files?

**Comment by ugocupcic** [comment]
Yes we'll skip them for now (they should be fixed directly in @Rocketmagnet code)

**Comment by Rocketmagnet** [comment]
Is it in the .h file? What are the errors?

On 1 October 2015 at 10:25, Ugo Cupcic notifications@github.com wrote:

> Yes we'll skip them for now (they should be fixed directly in
> @Rocketmagnet https://github.com/Rocketmagnet code)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/shadow-robot/sr-ronex/pull/206#issuecomment-144668243
> .

## 

---

_Shadow Robot Company Ltd._
251 Liverpool Road, N1 1LX, UK
Registered Number 3308007 (England & Wales)

RoNeX - Building Robots with ROS Made Easy 

## http://www.shadowrobot.com/products/ronex/

**Comment by ugocupcic** [comment]
They're available in circleci (see the red cross above the merge pull request button)?

Here's the copy of those errors:
https://gist.github.com/ugocupcic/b6db34437ebdfbb0f28e

**Comment by ugocupcic** [comment]
Thanks!!

**Pull request merged**
