### PR TITLE
F control all digital outputs

### PR DESCRIPTION
**Pull request by toliver**
Please DO NOT MERGE THIS YET!!!!!
Please, do #119 first.

### CODE REVIEW

**Comment by toliver** [comment]
Please DO NOT MERGE THIS YET!!!!!

**Comment by ugocupcic** [comment]
I merged #119

**Comment by toliver** [comment]
This was tested by Hugo last week, and seems to work well. So we can merge it as well.
Unless Ugo or Manos know otherwise.

**Comment by toliver** [comment]
Ok, Now the pull request diff is up to date.
This is ready to review/merge.

**Pull request merged**
