### PR TITLE
Fix issue no 97.

### PR DESCRIPTION
**Pull request by YiShadow**

### CODE REVIEW

**Comment by ugocupcic** [comment]
Once more....

Use, as the title:

Fixes #97 - Wrong variable name

**Comment by ugocupcic** [comment]
@markpitchless or @toliver don't we now need to add an item to the changelog each time we do a pull request on ronex?

**Comment by toliver** [comment]
I'd say that depends on how detailed do we want the changelog to be.
Definitely the relevant features and bugs solved should be there. I don't know if we want some obscure bugs and improvements to appear, though.

**Comment by toliver** [comment]
Oops, I merged without changelog :(

**Comment by ugocupcic** [comment]
it's probably OK. Let's add new features and important bug fixes to the changelog. Otherwise it's going to be huge

**Pull request merged**
